README.md: add links to issue types and issue templats
TrenchBoot/trenchboot-issues pull request #7
Opened 2023-02-28 15:38 UTC by macpijan

2023-02-28 15:52 UTC, dpsmith approved these changes

2023-03-01 15:33 UTC, pietrushnic requested changes

2024-01-30 23:49 UTC, pietrushnic commented
@macpijan it would be great to merge it before FOSDEM24

2024-08-06 13:10 UTC, krystian-hebel commented on README.md
>  * [Contributing](https://github.com/TrenchBoot/documentation/blob/master/CONTRIBUTING.md)
@macpijan ping

2024-08-21 13:15 UTC, SergiiDmytruk commented on README.md
>  * [Contributing](https://github.com/TrenchBoot/documentation/blob/master/CONTRIBUTING.md)
I've added it: https://github.com/TrenchBoot/trenchboot-issues/pull/7/commits/8015ee786cd536cf4a30dea87fabee6d462026f5

2024-08-30 22:21 UTC, SergiiDmytruk commented on README.md
>  * [Contributing](https://github.com/TrenchBoot/documentation/blob/master/CONTRIBUTING.md)
@pietrushnic, ping.

2024-08-31 07:34 UTC, pietrushnic approved these changes

2024-08-31 13:37 UTC, merged